/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as CagnotteVaultContractJson } from "../CagnotteVault.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace CagnotteVaultTypes {
  export type Fields = {
    admin: Address;
    isSuperTaskDone: boolean;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    deposit: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    releaseToWinner: {
      params: CallContractParams<{ winner: Address }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    deposit: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    releaseToWinner: {
      params: SignExecuteContractMethodParams<{ winner: Address }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  CagnotteVaultInstance,
  CagnotteVaultTypes.Fields
> {
  encodeFields(fields: CagnotteVaultTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  at(address: string): CagnotteVaultInstance {
    return new CagnotteVaultInstance(address);
  }

  tests = {
    deposit: async (
      params: Omit<
        TestContractParamsWithoutMaps<CagnotteVaultTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    releaseToWinner: async (
      params: TestContractParamsWithoutMaps<
        CagnotteVaultTypes.Fields,
        { winner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "releaseToWinner", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: CagnotteVaultTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const CagnotteVault = new Factory(
  Contract.fromJson(
    CagnotteVaultContractJson,
    "",
    "97e5652dc6b50209e998a2765c5a09ecd610e3f4a78d6a1b7e341da1ebc689ec",
    []
  )
);
registerContract(CagnotteVault);

// Use this class to interact with the blockchain
export class CagnotteVaultInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CagnotteVaultTypes.State> {
    return fetchContractState(CagnotteVault, this);
  }

  view = {
    deposit: async (
      params?: CagnotteVaultTypes.CallMethodParams<"deposit">
    ): Promise<CagnotteVaultTypes.CallMethodResult<"deposit">> => {
      return callMethod(
        CagnotteVault,
        this,
        "deposit",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    releaseToWinner: async (
      params: CagnotteVaultTypes.CallMethodParams<"releaseToWinner">
    ): Promise<CagnotteVaultTypes.CallMethodResult<"releaseToWinner">> => {
      return callMethod(
        CagnotteVault,
        this,
        "releaseToWinner",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    deposit: async (
      params: CagnotteVaultTypes.SignExecuteMethodParams<"deposit">
    ): Promise<CagnotteVaultTypes.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(CagnotteVault, this, "deposit", params);
    },
    releaseToWinner: async (
      params: CagnotteVaultTypes.SignExecuteMethodParams<"releaseToWinner">
    ): Promise<
      CagnotteVaultTypes.SignExecuteMethodResult<"releaseToWinner">
    > => {
      return signExecuteMethod(CagnotteVault, this, "releaseToWinner", params);
    },
  };
}
