/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as HackathonEscrowContractJson } from "../HackathonEscrow.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace HackathonEscrowTypes {
  export type Fields = {
    owner: Address;
    systemAdmin: Address;
    targetTasks: bigint;
    completedTasks: bigint;
    lockedAmount: bigint;
  };

  export type State = ContractState<Fields>;

  export type TaskCompletedEvent = ContractEvent<{ count: bigint }>;
  export type FundsReleasedEvent = ContractEvent<{
    to: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    completeOneTask: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    completeOneTask: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  HackathonEscrowInstance,
  HackathonEscrowTypes.Fields
> {
  encodeFields(fields: HackathonEscrowTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { TaskCompleted: 0, FundsReleased: 1 };

  at(address: string): HackathonEscrowInstance {
    return new HackathonEscrowInstance(address);
  }

  tests = {
    completeOneTask: async (
      params: Omit<
        TestContractParamsWithoutMaps<HackathonEscrowTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "completeOneTask", params, getContractByCodeHash);
    },
    withdraw: async (
      params: Omit<
        TestContractParamsWithoutMaps<HackathonEscrowTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: HackathonEscrowTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const HackathonEscrow = new Factory(
  Contract.fromJson(
    HackathonEscrowContractJson,
    "",
    "554ce71ac667ec362f6fb77b751e695b006a7820148f7c9a4f6ed54e87c41be3",
    []
  )
);
registerContract(HackathonEscrow);

// Use this class to interact with the blockchain
export class HackathonEscrowInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<HackathonEscrowTypes.State> {
    return fetchContractState(HackathonEscrow, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeTaskCompletedEvent(
    options: EventSubscribeOptions<HackathonEscrowTypes.TaskCompletedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      HackathonEscrow.contract,
      this,
      options,
      "TaskCompleted",
      fromCount
    );
  }

  subscribeFundsReleasedEvent(
    options: EventSubscribeOptions<HackathonEscrowTypes.FundsReleasedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      HackathonEscrow.contract,
      this,
      options,
      "FundsReleased",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | HackathonEscrowTypes.TaskCompletedEvent
      | HackathonEscrowTypes.FundsReleasedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      HackathonEscrow.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    completeOneTask: async (
      params?: HackathonEscrowTypes.CallMethodParams<"completeOneTask">
    ): Promise<HackathonEscrowTypes.CallMethodResult<"completeOneTask">> => {
      return callMethod(
        HackathonEscrow,
        this,
        "completeOneTask",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params?: HackathonEscrowTypes.CallMethodParams<"withdraw">
    ): Promise<HackathonEscrowTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        HackathonEscrow,
        this,
        "withdraw",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    completeOneTask: async (
      params: HackathonEscrowTypes.SignExecuteMethodParams<"completeOneTask">
    ): Promise<
      HackathonEscrowTypes.SignExecuteMethodResult<"completeOneTask">
    > => {
      return signExecuteMethod(
        HackathonEscrow,
        this,
        "completeOneTask",
        params
      );
    },
    withdraw: async (
      params: HackathonEscrowTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<HackathonEscrowTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(HackathonEscrow, this, "withdraw", params);
    },
  };
}
