/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as CompleteTaskScriptScriptJson } from "../CompleteTaskScript.ral.json";

export const CompleteTaskScript = new ExecutableScript<{ escrow: HexString }>(
  Script.fromJson(CompleteTaskScriptScriptJson, "", []),
  getContractByCodeHash
);
