/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as ForfeitScriptScriptJson } from "../ForfeitScript.ral.json";
import { default as WithdrawScriptScriptJson } from "../WithdrawScript.ral.json";

export const ForfeitScript = new ExecutableScript<{ escrow: HexString }>(
  Script.fromJson(ForfeitScriptScriptJson, "", []),
  getContractByCodeHash
);

export const WithdrawScript = new ExecutableScript<{ escrow: HexString }>(
  Script.fromJson(WithdrawScriptScriptJson, "", []),
  getContractByCodeHash
);
